adapt PlotHandler to use (x,y)-Tupels
HPI-ELEA/elea pull request #113
Opened 2022-05-06 11:18 UTC by kohlros

PlotWorkers now save the data in {xValue,yValue}-Objects to allow for an x-y-plotting block.

2022-05-10 14:09 UTC, antonykamp requested changes

2022-05-10 14:09 UTC, antonykamp commented on static/scripts/PlotHandler.js
> +            if (data.xValue == null) {
If you want, you can use simply type `if(!data.xValue)`

2022-05-11 15:16 UTC, kohlros commented on static/scripts/newblocks.js
> +  var code = "plot({xValue: null, yValue: ";
I am not sure how it can be avoided.

2022-05-12 09:08 UTC, antonykamp commented on static/scripts/newblocks.js
> +  var code = "plot({xValue: null, yValue: ";
Just leave it out :D `data.xValue` should be `null` per default, if you don't declare it

2022-05-15 18:37 UTC, kohlros commented on static/scripts/PlotHandler.js
> +                            beginAtZero: true,
It doesn't. However if the x-Axis isn't mentioned in the setup, linegraphs aren't drawn properly and I don't know why. I will take a look into this in the PR where plotting-optics are improved.

2022-05-15 18:39 UTC, antonykamp approved these changes

2022-05-15 18:39 UTC, merged